# Generated by Django 5.2.15 on 2026-09-08 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.IntegerField(max_length=20, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Заявка на звонок',
                'verbose_name_plural': 'Заявки на звонок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО врача')),
                ('specialty', models.CharField(max_length=150, verbose_name='Специализация')),
                ('photo', models.ImageField(upload_to='doctors/', verbose_name='Фотография')),
                ('appointment_url', models.URLField(blank=True, default='#', max_length=500, verbose_name='Ссылка на запись')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='OmsApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birthdate', models.DateField(max_length=50, verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.IntegerField(max_length=50, verbose_name='Телефон')),
                ('service', models.CharField(max_length=100, verbose_name='Услуга')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион')),
                ('doctor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Врач')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина обращения')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник')),
                ('file', models.FileField(blank=True, null=True, upload_to='oms_files/', verbose_name='Документы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Заявка на ОМС',
                'verbose_name_plural': 'Заявки на ОМС',
            },
        ),
        migrations.CreateModel(
            name='OmsDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название направления')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('link', models.URLField(default='#', max_length=500, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Направление ОМС',
                'verbose_name_plural': 'Направления ОМС',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('doctor', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateField()),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название направления')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Изображение')),
                ('link_url', models.URLField(blank=True, default='#', verbose_name='Ссылка/URL')),
            ],
            options={
                'verbose_name': 'Направление работы',
                'verbose_name_plural': 'Направления нашей работы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('direction', models.CharField(max_length=150, verbose_name='Направление')),
                ('appointment_date', models.DateField(blank=True, null=True, verbose_name='Дата приема')),
                ('appointment_time', models.TimeField(blank=True, null=True, verbose_name='Время приема')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('done', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Заявка на прием',
                'verbose_name_plural': 'Заявки на прием',
                'ordering': ['-created_at'],
            },
        ),
    ]
