# Generated by Django 5.2.15 on 2026-06-26 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Пусто — услуга доступна во всей сети', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.clinic', verbose_name='Клиника'),
        ),
    ]
