# Generated by Django 5.2.10 on 2026-07-02 11:06

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_clinic_slugs(apps, schema_editor):
    Clinic = apps.get_model('clinics', 'Clinic')
    for clinic in Clinic.objects.all():
        base_slug = slugify(clinic.name) or f'clinic-{clinic.pk}'
        slug = base_slug
        suffix = 2
        while Clinic.objects.filter(slug=slug).exclude(pk=clinic.pk).exists():
            slug = f'{base_slug}-{suffix}'
            suffix += 1
        clinic.slug = slug
        clinic.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_servicecategory_clinicuser_doctor_clinic_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='is_branch',
            field=models.BooleanField(default=False, verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='parent_clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='clinics.clinic', verbose_name='Главная клиника'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.RunPython(populate_clinic_slugs, migrations.RunPython.noop),
        migrations.AddField(
            model_name='clinic',
            name='working_hours',
            field=models.CharField(blank=True, max_length=120, verbose_name='Часы работы'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='clinics.servicecategory', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Стаж лет'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, verbose_name='Квалификация'),
        ),
        migrations.CreateModel(
            name='DoctorScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Начало')),
                ('end_at', models.DateTimeField(verbose_name='Окончание')),
                ('is_available', models.BooleanField(default=True, verbose_name='Свободно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='clinics.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Слот расписания',
                'verbose_name_plural': 'Слоты расписания',
                'ordering': ['start_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinics.doctorscheduleslot', verbose_name='Слот расписания'),
        ),
    ]
