# Generated by Django 5.2.15 on 2026-07-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_clinic_city_clinic_is_branch_clinic_parent_clinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='Слаг'),
        ),
    ]
