# Generated by Django 5.2.15 on 2026-08-17 15:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_alter_clinic_slug_alter_servicecategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('callback', 'Заказать звонок'), ('appointment', 'Записаться на приём')], default='callback', max_length=20, verbose_name='Тип заявки')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки на обратный звонок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.CharField(blank=True, help_text='Имя файла в static/img', max_length=200, verbose_name='Изображение (файл в static/img)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Акция действует до')),
                ('image', models.CharField(blank=True, help_text='Имя файла, например 2cf9f4594d091cb8c094edd35e77a980b8f7187a.png', max_length=200, verbose_name='Изображение (файл в static/img)')),
                ('color', models.CharField(blank=True, help_text='HEX без #, например 27c78a. Пусто — обычная белая карточка.', max_length=20, verbose_name='Цвет карточки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.CharField(blank=True, help_text='Имя файла, например 27d078fc5f910ac9b6a38deb4edd56162a412c8a.png', max_length=200, verbose_name='Фото (файл в static/img)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.CharField(blank=True, help_text='Имя файла, например bd4b3cb5032c02f54b1f78de3cea6bf20051a4e9.png', max_length=200, verbose_name='Изображение (файл в static/img)'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150, verbose_name='Имя пациента')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка (1–5)')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='clinics.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
