# Generated by Django 5.2.15 on 2026-09-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='appointment_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Ссылка на запись'),
        ),
        migrations.AlterField(
            model_name='omsdirection',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='servicedirection',
            name='link_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка/URL'),
        ),
    ]
