from django.urls import path
from .views import (
    home_view,
    oms_page,
    dms_page,
    direction_page,
    analysis_page,
    promotions_page,
    informations_page,
    about_the_clinic,
    save_callback,
    contact_page,
    DoctorListView,
    DoctorDetailView,
    DoctorCreateView,
    DoctorUpdateView,
    DoctorDeleteView,
    ServiceDirectionListView,
    ServiceDirectionDetailView,
    ServiceDirectionCreateView,
    ServiceDirectionUpdateView,
    ServiceDirectionDeleteView,
    ReviewListView,
    ReviewDetailView,
    ReviewCreateView,
    ReviewUpdateView,
    ReviewDeleteView,
)

urlpatterns = [
    path("", home_view, name="home"),
    path('doctors/', DoctorListView.as_view(), name='doctors_list'),
    path('doctors/create/', DoctorCreateView.as_view(), name='doctor_create'),
    path('doctors/<int:pk>/', DoctorDetailView.as_view(), name='doctor_detail'),
    path('doctors/<int:pk>/update/', DoctorUpdateView.as_view(), name='doctor_update'),
    path('doctors/<int:pk>/delete/', DoctorDeleteView.as_view(), name='doctor_delete'),
    path('services/', ServiceDirectionListView.as_view(), name='services_list'),
    path('services/create/', ServiceDirectionCreateView.as_view(), name='service_create'),
    path('services/<int:pk>/', ServiceDirectionDetailView.as_view(), name='direction_detail'),
    path('services/<int:pk>/update/', ServiceDirectionUpdateView.as_view(), name='service_update'),
    path('services/<int:pk>/delete/', ServiceDirectionDeleteView.as_view(), name='service_delete'),
    path('oms/', oms_page, name='oms_page'),
    path('dms/', dms_page, name='dms_page'),
    path('direction/', direction_page, name='direction_page'),
    path('analysis/', analysis_page, name='analysis_page'),
    path('promotions/', promotions_page, name='promotions_page'),
    path('informations/', informations_page, name='informations_page'),
    path('about/', about_the_clinic, name='about_the_clinic'),
    path('save-callback/', save_callback, name='save_callback'),
    path('reviews/', ReviewListView.as_view(), name='reviews'),
    path('reviews/create/', ReviewCreateView.as_view(), name='review_create'),
    path('reviews/<int:pk>/', ReviewDetailView.as_view(), name='review_detail'),
    path('reviews/<int:pk>/update/', ReviewUpdateView.as_view(), name='review_update'),
    path('reviews/<int:pk>/delete/', ReviewDeleteView.as_view(), name='review_delete'),
    path('contacts/', contact_page, name='contact_page'),
]
